import NavBarNabigation from "@/component/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My Next JS App for practice</title>
      </head>
      <body>
        <header>
          <NavBarNabigation />
        </header>
        {children}
      </body>
    </html>
  );
}
